spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=Pass123a
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway will look in db/migration by default
spring.flyway.enabled=true

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true